#!/usr/bin/python


import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import sys

matplotlib.rcParams.update({'font.size': 18})
matplotlib.rcParams['font.family'] = "Bitstream Vera Serif"
fig = plt.figure() # create figure
fig.subplots_adjust(0.2,0.2)
fig.set_facecolor("white")



name = sys.argv[1]
m = np.genfromtxt(name).transpose()

plt.plot(m[0],m[1],marker="o",c="blue")
plt.xlabel("Site")
plt.ylabel("<S_i S_j>")
plt.show()


