#!/usr/bin/python2


import matplotlib.pyplot as plt
import sys
import numpy as np
import matplotlib
matplotlib.rcParams.update({'font.size': 18})
matplotlib.rcParams['font.family'] = "Bitstream Vera Serif"
fig = plt.figure()
fig.subplots_adjust(0.2,0.2)




fig.set_facecolor("white")

name = sys.argv[1]  # name of the file

m = np.genfromtxt(name).transpose()
x = m[0]
y = m[1]
z = np.abs(m[2]+1j*m[3])

# get dimensions assuming uniform grid

  
ny = (y.max()-y.min())/abs(y[1]-y[0])
ny = int(round(ny)) + 1
nx = len(z)/ny

nx = int(nx)
ny = int(ny)

#nx = 20
#ny = len(z)//nx



print("Detected",nx,ny,"grid")

Z = np.abs(z).reshape(nx,ny) # makes a (Zy,Zx) matrix out of z
Z = z.reshape(nx,ny) # makes a (Zy,Zx) matrix out of z
T = Z.T              # transposes the matrix (Zx,Zy)

# now interpolate to get a smooth mesh
from scipy.interpolate import interp2d
x = np.linspace(0.,1.,nx)
y = np.linspace(0.,1.,ny)
xx, yy = np.meshgrid(x, y)
f = interp2d(x, y, T, kind='linear')

# 
x = np.linspace(0.,1.,1000)
y = np.linspace(0.,1.,1000)

z_inter = f(x,y)


# now plot the data

vmax = np.percentile(z_inter,95)

minx = np.min(m[0])
maxx = np.max(m[0])
miny = np.min(m[1])
maxy = np.max(m[1])
plt.imshow(z_inter, aspect='auto', origin='lower',cmap = plt.get_cmap("hot"), extent = ( minx, maxx, miny, maxy),interpolation='nearest',vmax=vmax)

plt.xlabel("$ |\\langle S_n \delta(\omega - H +E_0) S_m \\rangle |$")
plt.ylabel("$\omega$ [J]")


plt.show()
