#!/usr/bin/python


import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import sys

matplotlib.rcParams.update({'font.size': 18})
matplotlib.rcParams['font.family'] = "Bitstream Vera Serif"
fig = plt.figure() # create figure
fig.subplots_adjust(0.2,0.2)
fig.set_facecolor("white")



name = sys.argv[1]
m = np.genfromtxt(name).transpose()

plt.plot(m[0],m[1],c="blue",label="Real",linewidth=4)
plt.plot(m[0],m[2],c="red",label="Imag",linewidth=4)
plt.xlabel("Frequency [J]")
plt.ylabel("$<S_i\delta (\omega - H -E_0) S_j>$")
plt.legend()
plt.show()


