#!/usr/bin/python


import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import sys

matplotlib.rcParams.update({'font.size': 18})
matplotlib.rcParams['font.family'] = "Bitstream Vera Serif"
fig = plt.figure() # create figure
fig.subplots_adjust(0.2,0.2)
fig.set_facecolor("white")



# get the label for the y axis
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--ylabel",default="XX")
parser.add_argument("--input",default="STATIC_CORRELATOR.OUT")
args = parser.parse_args() # get the arguments
name = args.input # input file
# define the ylabel
bra = "$\\langle GS |"
ket = "| GS \\rangle$"
delta = "\\delta (\\omega - H +E_0)"
if args.ylabel=="XX": ylabel = bra+"S^x_i"+delta+" S^x_j"+ket
elif args.ylabel=="YY": ylabel = bra+"S^y_i"+delta+" S^y_j"+ket
elif args.ylabel=="ZZ": ylabel = bra+"S^z_i"+delta+" S^z_j"+ket
else: raise








m = np.genfromtxt(name).transpose()

plt.plot(m[0],m[1],c="blue",label="Real",linewidth=4)
plt.plot(m[0],m[2],c="red",label="Imag",linewidth=4)
plt.xlabel("Frequency [J]")
plt.ylabel(ylabel)
plt.legend()
plt.show()


