#!/usr/bin/python


import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import sys




# get the label for the y axis
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--input",default="EXCITED.OUT")
parser.add_argument("--ylabel",default="")
args = parser.parse_args() # get the arguments
if args.ylabel=="GS":  ylabel = "Energy - $E_{GS}$"
else:  ylabel = "Energy"
name = args.input # input file
# define the ylabel





matplotlib.rcParams.update({'font.size': 18})
matplotlib.rcParams['font.family'] = "Bitstream Vera Serif"
fig = plt.figure() # create figure
fig.subplots_adjust(0.2,0.2)
fig.set_facecolor("white")



es = np.genfromtxt(name) # get data

plt.scatter(range(len(es)),es,marker="o",c="blue",s=80)
for e in es:
  xs = np.linspace(-1,len(es)+1,20)
  plt.plot(xs,xs*0.+e,c="red")
plt.xlabel("Eigenstate index")
plt.ylabel(ylabel)
plt.xlim([-0.1,len(es)-0.9])
plt.show()


