# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(430, 10, 301, 351))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(30, 30, 255, 106))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_6.setObjectName("label_6")
        self.gridLayout_10.addWidget(self.label_6, 0, 0, 1, 1)
        self.type_static = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.type_static.setObjectName("type_static")
        self.type_static.addItem("")
        self.type_static.addItem("")
        self.type_static.addItem("")
        self.type_static.addItem("")
        self.gridLayout_10.addWidget(self.type_static, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_10.addWidget(self.label_7, 1, 0, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_10.addWidget(self.comboBox_5, 1, 1, 1, 1)
        self.get_static_correlator = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.get_static_correlator.setObjectName("get_static_correlator")
        self.gridLayout_10.addWidget(self.get_static_correlator, 2, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tabWidget_4.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.tab_12)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(40, 40, 160, 80))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget_7)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_13.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_12.setObjectName("label_12")
        self.gridLayout_13.addWidget(self.label_12, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.tab_13)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(40, 40, 191, 171))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_14.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.gridLayoutWidget_8)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout_14.addWidget(self.comboBox_6, 1, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_13, "")
        self.gridLayout_12.addWidget(self.tabWidget_4, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 361, 361))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 2)
        self.nsites = QtWidgets.QLineEdit(self.tab)
        self.nsites.setObjectName("nsites")
        self.gridLayout.addWidget(self.nsites, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.tab_6)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab_6)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 2, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tab_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.coupling_type = QtWidgets.QComboBox(self.tab_5)
        self.coupling_type.setObjectName("coupling_type")
        self.coupling_type.addItem("")
        self.coupling_type.addItem("")
        self.coupling_type.addItem("")
        self.coupling_type.addItem("")
        self.gridLayout_3.addWidget(self.coupling_type, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.coupling_modulation = QtWidgets.QComboBox(self.tab_5)
        self.coupling_modulation.setObjectName("coupling_modulation")
        self.coupling_modulation.addItem("")
        self.coupling_modulation.addItem("")
        self.gridLayout_3.addWidget(self.coupling_modulation, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_5)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.tab_7)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.XXZJ = QtWidgets.QLineEdit(self.tab_7)
        self.XXZJ.setObjectName("XXZJ")
        self.gridLayout_5.addWidget(self.XXZJ, 0, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_5.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_7)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.gridLayout_4.addWidget(self.tabWidget_3, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_4 = QtWidgets.QLabel(self.tab_9)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_9)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_3, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_9)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_7.addWidget(self.textEdit_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.tab_10)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(50, 50, 241, 211))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.maxm = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.maxm.setObjectName("maxm")
        self.gridLayout_11.addWidget(self.maxm, 0, 1, 1, 1)
        self.nsweeps = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.nsweeps.setObjectName("nsweeps")
        self.gridLayout_11.addWidget(self.nsweeps, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_10.setObjectName("label_10")
        self.gridLayout_11.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_11.setObjectName("label_11")
        self.gridLayout_11.addWidget(self.label_11, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_10, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_4.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(4)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Ground state"))
        self.label_6.setText(_translate("MainWindow", "Sweep type"))
        self.type_static.setItemText(0, _translate("MainWindow", "From edge"))
        self.type_static.setItemText(1, _translate("MainWindow", "From bulk"))
        self.type_static.setItemText(2, _translate("MainWindow", "First neighbor right"))
        self.type_static.setItemText(3, _translate("MainWindow", "First neighbor left"))
        self.label_7.setText(_translate("MainWindow", "Correlator"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "SS"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "XX"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "YY"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "ZZ"))
        self.get_static_correlator.setText(_translate("MainWindow", "Show"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Static"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("MainWindow", "Single"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Onsite"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "From edge"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "From bulk"))
        self.label_12.setText(_translate("MainWindow", "Type"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("MainWindow", "Map"))
        self.lineEdit.setText(_translate("MainWindow", "0.1"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "KPM"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "TD"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_13), _translate("MainWindow", "Params"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Dynamic"))
        self.label.setText(_translate("MainWindow", "# of sites"))
        self.pushButton_2.setText(_translate("MainWindow", "View geometry"))
        self.nsites.setText(_translate("MainWindow", "10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Geometry"))
        self.label_5.setText(_translate("MainWindow", "Table with the spins"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1/2"))
        self.comboBox.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3/2"))
        self.comboBox.setItemText(3, _translate("MainWindow", "2"))
        self.comboBox.setItemText(4, _translate("MainWindow", "1/2 & 1"))
        self.comboBox.setItemText(5, _translate("MainWindow", "1 & 1/2"))
        self.comboBox.setItemText(6, _translate("MainWindow", "1 & 3/2"))
        self.comboBox.setItemText(7, _translate("MainWindow", "3/2 & 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Spins"))
        self.label_2.setText(_translate("MainWindow", "Coupling type"))
        self.coupling_type.setItemText(0, _translate("MainWindow", "Heisenberg"))
        self.coupling_type.setItemText(1, _translate("MainWindow", "XXZ"))
        self.coupling_type.setItemText(2, _translate("MainWindow", "Ising"))
        self.coupling_type.setItemText(3, _translate("MainWindow", "Custom"))
        self.label_8.setText(_translate("MainWindow", "Modulation"))
        self.coupling_modulation.setItemText(0, _translate("MainWindow", "Uniform"))
        self.coupling_modulation.setItemText(1, _translate("MainWindow", "Dimerized"))
        self.label_3.setText(_translate("MainWindow", "XZZ coupling"))
        self.XXZJ.setText(_translate("MainWindow", "1.0"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "XXZ"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Custom"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Exchange"))
        self.label_4.setText(_translate("MainWindow", "Type"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Ferromagnetic"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Antiferromagnetic"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Fields"))
        self.maxm.setText(_translate("MainWindow", "10"))
        self.nsweeps.setText(_translate("MainWindow", "4"))
        self.label_10.setText(_translate("MainWindow", "Bond dimension"))
        self.label_11.setText(_translate("MainWindow", "# of sweeps"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "Params"))

